name: point2mesh
channels:
  - pytorch
  - defaults
  - conda-forge
  - fvcore
  - nvidia
dependencies:
  - python=3.8.10
  - numpy
  - fvcore=0.1
  - pip
  - pip:
    - pytest==5.4.2
    - torch==1.13.0
    - torchvision==0.14.0
    - open3d==0.17.0